# Generated by Django 6.0.3 on 2026-04-17 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('uid', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('user_type', models.CharField(blank=True, max_length=32, null=True)),
                ('checkin_frequency', models.CharField(blank=True, max_length=32, null=True)),
                ('grace_period_hours', models.IntegerField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=128, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('pin', models.CharField(blank=True, max_length=16, null=True)),
                ('last_check_in_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='ok', max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
    ]
