# Generated by Django 5.2.13 on 2026-04-23 18:08

from django.contrib.auth.hashers import identify_hasher, make_password
from django.db import migrations, models


def hash_existing_plaintext_pins(apps, schema_editor):
    UserProfile = apps.get_model('api', 'UserProfile')
    for user in UserProfile.objects.exclude(pin__isnull=True).exclude(pin=''):
        pin = (user.pin or '').strip()
        if not pin:
            continue
        try:
            identify_hasher(pin)
            continue
        except Exception:
            pass
        if pin.isdigit() and len(pin) == 4:
            user.pin = make_password(pin)
            user.save(update_fields=['pin'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile_full_name_usertimelineevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.RunPython(hash_existing_plaintext_pins, migrations.RunPython.noop),
    ]
