# Generated by Django 5.2.13 on 2026-04-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userprofile_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_country_code',
            field=models.CharField(default='UG', max_length=2),
        ),
    ]
